CREATE TABLE IF NOT EXISTS Users (
  UserId SERIAL PRIMARY KEY,
  FirstName VARCHAR (255),
  LastName VARCHAR (255),
  Email VARCHAR (255) UNIQUE,
  Password VARCHAR (255),
  Chips INTEGER,
  Avatar INTEGER
);

CREATE TABLE IF NOT EXISTS Games (
  GameId INTEGER PRIMARY KEY,
  MaxPlayers INTEGER,
  MinChips INTEGER,
  SeatsTaken INTEGER,
  Turn INTEGER
);

CREATE TABLE IF NOT EXISTS Players (
  GameId INTEGER REFERENCES Games(GameId),
  UserId INTEGER REFERENCES Users(UserId),
  Bid INTEGER,
  BuyIn INTEGER,
  NetGain INTEGER,
  IsPlaying BOOLEAN,
  SeatNumber INTEGER
);

CREATE TABLE IF NOT EXISTS Deck (
  CardId SERIAL PRIMARY KEY,
  Card VARCHAR(255),
  Image VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS PlayersCards (
  GameId INTEGER REFERENCES Games(GameId),
  UserId INTEGER REFERENCES Users(UserId),
  FlopCard1 INTEGER,
  FlopCard2 INTEGER,
  FlopCard3 INTEGER,
  TurnCard INTEGER,
  RiverCard INTEGER
);

CREATE TABLE IF NOT EXISTS PlayersActions (
  GameId INTEGER REFERENCES Games(GameId),
  UserId INTEGER REFERENCES Users(UserId),
  IsAllIn BOOLEAN,
  IsCall BOOLEAN,
  IsCheck BOOLEAN,
  IsFold BOOLEAN,
  IsRaise BOOLEAN
)
